# Generated by Django 4.0.3 on 2022-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='static/img/trend_img')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('img1', models.ImageField(null=True, upload_to='static/img/trend_img')),
                ('img2', models.ImageField(null=True, upload_to='static/img/trend_img')),
                ('img3', models.ImageField(null=True, upload_to='static/img/trend_img')),
                ('img4', models.ImageField(null=True, upload_to='static/img/trend_img')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=125, null=True, unique=True)),
            ],
        ),
    ]
