# Generated by Django 4.0.3 on 2022-03-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendpage', '0002_trendproduct_available_trendproduct_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendproduct',
            name='img',
        ),
    ]
