# Generated by Django 4.0.3 on 2022-03-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_logo', models.ImageField(upload_to='img')),
                ('company_type', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=10, null=True)),
                ('kg05', models.FloatField(blank=True, default=0, null=True)),
                ('kg1', models.FloatField(blank=True, default=0, null=True)),
                ('kg2', models.FloatField(blank=True, default=0, null=True)),
                ('kg3', models.FloatField(blank=True, default=0, null=True)),
                ('kg4', models.FloatField(blank=True, default=0, null=True)),
                ('kg5', models.FloatField(blank=True, default=0, null=True)),
                ('kg6', models.FloatField(blank=True, default=0, null=True)),
                ('kg7', models.FloatField(blank=True, default=0, null=True)),
                ('kg8', models.FloatField(blank=True, default=0, null=True)),
                ('kg9', models.FloatField(blank=True, default=0, null=True)),
                ('kg10', models.FloatField(blank=True, default=0, null=True)),
                ('kg11', models.FloatField(blank=True, default=0, null=True)),
                ('kg12', models.FloatField(blank=True, default=0, null=True)),
                ('kg13', models.FloatField(blank=True, default=0, null=True)),
                ('kg14', models.FloatField(blank=True, default=0, null=True)),
                ('kg15', models.FloatField(blank=True, default=0, null=True)),
                ('kg16', models.FloatField(blank=True, default=0, null=True)),
                ('kg17', models.FloatField(blank=True, default=0, null=True)),
                ('kg18', models.FloatField(blank=True, default=0, null=True)),
                ('kg19', models.FloatField(blank=True, default=0, null=True)),
                ('kg20', models.FloatField(blank=True, default=0, null=True)),
                ('kg_21_44', models.FloatField(blank=True, default=0, null=True)),
                ('kg_45_70', models.FloatField(blank=True, default=0, null=True)),
                ('kg_71_100', models.FloatField(blank=True, default=0, null=True)),
                ('kg_101_299', models.FloatField(blank=True, default=0, null=True)),
                ('kg_300_plus', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='save_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_price', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField(default=1, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.country')),
            ],
        ),
    ]
