# Generated by Django 4.0.3 on 2022-03-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_company_save_data_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kg1_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg2_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg3_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg4_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg5_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg6_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg7_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg8_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='kg9_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
